# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  cake918小屋
subtitle: 数卷禅宗语，几点相思泪。佛曰：觉有情！
name: cake918 
email: cake918@126.com
description: start from here.
keywords: JAVA LIVE
encoding: "utf-8"
favicon: favicon.ico 

repository: caukie/caukie.github.io
github_url: https://github.com/caukie
url: http://caukie.github.io
enforce_ssl: caukie.github.io

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /life.html
    label: 故事
    target: _self


  -



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /archives.html
    label: Archives
    target: _self


# labels. my blog key words
labels:

  -

# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Design Patterns]
skill_j2ee_keywords: [Spring, Hibernet, MyBatis]

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#     username: caukie
# https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: caukie
#     repo: blog-comments
#     oauth:
#         client_id: 9df91bee22ece2c5627b
#         client_secret: fefcdd63ea2d514d52d6c49ca7502dd80637fd3e
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: caukie
    repo: caukie.github.io
    clientID: 9df91bee22ece2c5627b
    clientSecret: fefcdd63ea2d514d52d6c49ca7502dd80637fd3e
    id: md5(window.location.pathname)
# 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : true