publishDir: "docs"
baseURL: http://caukie.github.io
disablePathToLower: true
languageCode: zh-CN
title: cake918小屋
theme: "maupassant"

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false

params:
  author: "cake918"
  subtitle: "个人"
  keywords: "生活，技术"
  description: "数卷禅宗语，几点相思泪！佛曰：觉有情！"

 